language: node_js

node_js:
  - lts/*

matrix:
  fast_finish: true

cache:
  directories:
    - node_modules

deploy:
  provider: npm
  email: adrian.plavka@gmail.com
  api_key:
    secure: gseGiD/0nTfKoESWizJqQ8CqGfOCZG+bMmTZhSWoEcT8sFCMY2MrWQjkAjB9G8CprtX4z9fNBDy3GfYrzvIQN7apddfhNOpP8yOpatyySyxT0MjLobaTKqwK9dK9YXiZbPPgBsodZXYIEJaM6aNx6FVuaQqyTzwLOLHpOiNShitraQHpwEUZEfCM/k6+DC+WskQi3qa9qWEQ8ZJEDxlD5f8L09n9b9aIpoPhswKb1tghPYxzSucd3mfIi3O2onqAeL6BQLkD46RIPG7IhIz7359WGkb2a1/vzweDWZ8wKWCG+jG0GCMQrjXUBaF0VCktBrEXtlCmbJrXdP9b5lZH2sd9+KDFFbXWp79YrdQU4OJe1denkYdeEtKQRcjiXmUFbXqg5hMhIU7iNUeqkBb9k7yT7iPcSuaoDfwNgj82T9bgNcSu8zTPl+xAv3mfp7wBU6s/YtyilGCJ76cyybWKnoIebh3kMT1895Tp33H8RHLXLOofyhikQsAsrevg5dnLzD1HENxPPFjbaq1uAyOQB4Heuv4uyJ+z9xXcZemTSNuf+Cu77SVJ1dpfzu2xpHKK5mxVXgpSilEf1JImfWlb7+TKcqnNKsGGMP/n1FZB10vOjvjSzX29M9UDTS1TLiNU/EW9pg1OJzN0i++RHw9CUKDIkdpm5HotAPsqq3MCfEY=
  on:
    tags: true
